// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxW6oFuIxr6esefcsoYKMFqToavwx40dM',
    appId: '1:1006309016934:web:f8e3d9f49d3c92d6fc74a7',
    messagingSenderId: '1006309016934',
    projectId: 'online-groceries-c1aa2',
    authDomain: 'online-groceries-c1aa2.firebaseapp.com',
    storageBucket: 'online-groceries-c1aa2.appspot.com',
    measurementId: 'G-T8XBEJ3BFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgXhYvvFyc1Rd4FcWhAg3X2zHafZiPn0',
    appId: '1:1006309016934:android:412af8ac0f0a5da1fc74a7',
    messagingSenderId: '1006309016934',
    projectId: 'online-groceries-c1aa2',
    storageBucket: 'online-groceries-c1aa2.appspot.com',
  );
}
